name: pcm_mobile
description: Ứng dụng Mobile cho CLB Pickleball "Vợt Thủ Phố Núi" (PCM)
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # HTTP & Auth
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2

  # UI & Calendar
  table_calendar: ^3.1.2
  intl: ^0.19.0

  # Loading & Skeleton
  flutter_spinkit: ^5.2.1
  skeletonizer: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.3
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_pcm.png   # nếu có logo, thêm vào thư mục này